#!/bin/bash

# Get the current file name from the command line argument
file_name=$1

# Check if the file exists
if [ -f "$file_name" ]; then
    # Get the file extension
    extension="${file_name##*.}"

    # Check if the file is a C++ source file
    if [ "$extension" == "cpp" ] || [ "$extension" == "cxx" ] || [ "$extension" == "cc" ]; then
        # Compile the C++ source file
        echo "Compiling $file_name..."

        dsa_prep_dir="$(dirname "$(dirname $file_name)")"
        exec="$dsa_prep_dir/exec"
        only_file_name="$(basename $file_name)"
        only_file_name_without_extension="${only_file_name%.*}"

        # g++ -o "$exec/$only_file_name_without_extension" "$file_name"
        g++ -std=c++17 -Wall -Wextra -Wshadow -Wno-unused-result -Wconversion -Wfloat-equal -Wformat=2 -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2 -fsanitize=address -fsanitize=undefined -fno-sanitize-recover -fstack-protector -o "$exec/$only_file_name_without_extension" "$file_name"

        # Check if the compilation was successful
        if [ $? -eq 0 ]; then
            # Run the compiled program
            echo "Running ${file_name%.*}..."
            "$exec/$only_file_name_without_extension"
        else
            echo "Compilation failed!"
        fi
    else
        echo "File is not a C++ source file."
    fi
else
    echo "File not found."
fi
